### ISSUE TITLE
Better syntax highlighting for classes.

### ISSUE THREAD

**Issue by s-mark-holmes-ii** [Foxhoundn/synthax-code-theme#1]
I love this theme and I appreciate the work you have put into it thus far. I was wondering if you are planning on providing better syntax highlighting for classes.

<img width="579" alt="screen shot 2019-02-04 at 1 59 04 pm" src="https://user-images.githubusercontent.com/5240571/52230353-2d764d80-2885-11e9-80e6-b8495e135622.png">

In this case I would expect "class", "extends", and each individual method name to be colored differently. Thoughts?

**Comment by Foxhoundn** [comment]
Hey and thanks for the kind words!

Any chance you are using extension other than .js or .jsx? .ts perhaps?

**Comment by s-mark-holmes-ii** [comment]
@Foxhoundn Nope. Just a `.jsx` extension.

**Comment by Foxhoundn** [comment]
@smlmrkhlms Sorry for the delay, was on holiday last week.

I see that you are using both Operator Mono & Fira Code - that means you're probably using Custom CSS extension that injects CSS right?

**Comment by s-mark-holmes-ii** [comment]
@Foxhoundn This is no longer an issue. It seems as though there was a problem with one of the syntax highlighter plugins I was using for VSCode. Sorry for the confusion.
